apiVersion: v1
kind: Pod
metadata:
  name: flipkart
  labels:
    team: project
    department: dev
spec:
  containers:
    - name: signup
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo flipkart; sleep 2; done"]
